/**
 * Derivative paths for astrophotography images.
 *
 * Images are served unoptimized (next.config.js), so the raw file is
 * downloaded for every <Image>. Derivatives are pre-generated by
 * scripts/generate-astro-thumbs.js into subdirectories of /img/Astro:
 *   thumbs/ - grid cards and masonry (~1200px)
 *   medium/ - detail view and lightbox (~2560px)
 */

const ASTRO_DIR = '/img/Astro/';

function derive(src: string, tier: 'thumbs' | 'medium'): string {
  if (!src.startsWith(ASTRO_DIR)) return src;
  const rest = src.slice(ASTRO_DIR.length);
  if (rest.includes('/')) return src; // already inside a subdirectory
  return `${ASTRO_DIR}${tier}/${rest}`;
}

export const astroThumb = (src: string) => derive(src, 'thumbs');
export const astroMedium = (src: string) => derive(src, 'medium');
