name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Debug Node.js and npm versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: |
          npm ci --prefer-offline
          npm list

      - name: Install and Build
        run: |
          echo "Installing dependencies..."
          npm ci
          
          echo "Running build..."
          npm run build
          
          echo "Preparing deployment directory..."
          mkdir -p out
          
          # Copy public files
          if [ -d "public" ]; then
            echo "Copying public directory contents..."
            cp -r public/. out/
          fi
          
          # Ensure .nojekyll exists
          touch out/.nojekyll
          
          echo "Build directory contents:"
          ls -la
          
          echo "Out directory contents:"
          ls -la out/
          
          echo "Next.js output directory:"
          ls -la .next/standalone/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: out
          clean: true
          clean-exclude: |
            CNAME
            .nojekyll
            **/*
          commit-message: 'Deploy to GitHub Pages - $(date)'
          tag: v1.0.0
          tag-message: 'Deployed v1.0.0 - $(date)'

      - name: Upload build artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            out/
            .next/
            npm-debug.log*
            yarn-debug.log*
            yarn-error.log*
